version: '3.1'
services:
  stats-server:
    build: ewmStat
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1705448

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5466:5432"
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1705448

  ewm-service:
    build: ewmServer
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_server_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1705448
      - EWMSTAT_URL=http://stats-server:9090/

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_DB=ewm_server_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1705448
